### ISSUE TITLE
Uncaught exception due to template file doesn't exist (but it actually exists) . 

### ISSUE THREAD

**Issue by rpkoller** [titpetric/minitpl#1]
I run into the following issues from time to time and not entirely sure how to reproduce it yet. On my local mamp install everything works like a charm but as soon as i put things on a staging server it happens from time to time that i run into a fatal error. 

I've installed minitpl alongsde validator from respect with composer. On my local install i am running latest mamp version with php 5.6.x while on the staging server a php version > 5.3. is running. the basic system requirements are met. The odd thing is one time it works on the staging server then i make a few changes locally sync it to the staging server and then i run into the following error: 

```
Fatal error: Uncaught exception 'Exception' with message 'Template file 'form.tpl' doesn't exist! Is the compile dir writable?' in /home/myweb/public_html/vendor/monotek/minitpl/code/Monotek/MiniTPL/Template.php:84 Stack trace: #0 /home/myweb/public_html/lib/form.php(81): Monotek\MiniTPL\Template->load('form.tpl') #1 /home/myweb/public_html/index.php(1120): include_once('/home/gff-web/p...') #2 {main} thrown in /home/myweb/public_html/vendor/monotek/minitpl/code/Monotek/MiniTPL/Template.php on line 84
```

The odd thing is the template is there and it worked in the exact same setup before. I have no slight idea what is causing that jumpy behaviour. :/ 

At the beginning i require the composer php autoloader. then i instantiate the validator and minitpl class

``` php
$validator = new Respect\Validation\Validator;
$tpl = new Monotek\MiniTPL\Template;
```

and later a form is built with a form template: 

``` php
$tpl->load("form.tpl");
$tpl->assign("questiondraw", $questiondraw);
$tpl->assign("randquestion", $randquestion);
$tpl->assign("formerrorclass", $formerrorclass);
$tpl->assign("labelerrorclass", $labelerrorclass);
$tpl->assign("errors", $errors);
$tpl->assign("data", $data);
$tpl->assign("labels", $labels);
```

the error is thrown at the form.tpl load position. I don't know if it would make sense to post the complete form.php code or what other measures would makes sense to debug the issue. Is that a known problem? Best regards Ralf

**Comment by titpetric** [comment]
Hi,

do you set $tpl->_nocache and use the {_nocache_} features of MiniTPL? Generally recommended to leave those alone, leaving sane defaults. If you set _nocache=true for development, it creates a race condition, which might be the cause of the error you are seeing.

If you're setting any options between "$tpl = new ..." and "$tpl->load...", paste them here, if I see something "off".

Have you excluded possible file system issues like failing disk or running out of disk space? :)

Best,
Tit

**Comment by rpkoller** [comment]
Hi Tit, thanks for the quick reply! _nocache I haven't had set. The only difference between local and staging environment, aside the PHP version, is that i use Codekit alongside Mamp and that the former irons out any kind of caching and prohibits it. And about a failing disk or running out of disk space i am not aware of, but i will investigate further. In the meantime the used snippet looks the following: 

``` php
$errors = array();
$data = array();
$labels = array();
$maildelivered = false;
$tpl = new Monotek\MiniTPL\Template;
$validator = new Respect\Validation\Validator;

$data["formname"] = isset($_POST["formname"]) ? $_POST["formname"] : '';
$data["formphone"] = isset($_POST["formphone"]) ? $_POST["formphone"] : '';
$data["formmail"] = isset($_POST["formmail"]) ? $_POST["formmail"] : '';
$data["formabout"] = isset($_POST["formabout"]) ? $_POST["formabout"] : '';
$data["formcomment"] = isset($_POST["formcomment"]) ? $_POST["formcomment"] : '';
$data["formcheck"] = isset($_POST["formcheck"]) ? $_POST["formcheck"] : '';

$questions = array(
    array("Four plus seven (numeric value)", 11),
    array("One plus one (numeric value)", 2)
);

$questioncount = count($questions) - 1;
$randquestion = rand(0, $questioncount);
$questiondraw = $questions[$randquestion][0];

$givenAnswer = -1;
$rightAnswer = -2;

$formerrorclass = 'form__error--form';
$labelerrorclass = "form__error--label";

$labels["formname"] = "Sender";
$labels["formphone"] = "Phone Number";
$labels["formmail"] = "E-Mail";
$labels["formabout"] = "About";
$labels["formcomment"] = "Comment";
$labels["formcheck"] = $questiondraw;

if( isset( $_POST['send'] ) && $maildelivered == false ) {

    if((int)$_POST["formcheck"]){
        $rightAnswer = $questions[$_POST["randquestion"]][1];
        $givenAnswer = $_POST["formcheck"];
    }
    if( !$data["formname"] || !$validator::alnum('-.&\'ßüÜöÖäÄáÁéÉíÍóÓúÚàÀèÈìÌòÒùÙâÂêÊîÎôÔûÛ')->length(3,100)->validate( $data["formname"] ) ){
        $errors["formname"] = "Please enter a valid name";
        $labels["formname"] = $errors["formname"];
    }
    if( $data["formphone"] && !$validator::phone()->validate( $data["formphone"] ) ){
        $errors['formphone'] = "Please enter a valid phone number";
        $labels["formphone"] = $errors['formphone'];
    }
    if( !$data["formmail"] || !$validator::email()->validate( $data["formmail"] ) ){
        $errors['formmail'] = "Please enter a valid e-mail address";
        $labels["formmail"] = $errors['formmail'];
    }
    if( $data["formabout"] && !$validator::alnum('.?!…-:()ßüÜöÖäÄáÁéÉíÍóÓúÚàÀèÈìÌòÒùÙâÂêÊîÎôÔûÛ')->length(0,250)->validate( $data["formabout"] ) ){
        $errors['formabout'] = "Please enter a valid name";
        $labels["formabout"] = $errors['formabout'];
    }
    if( !$data["formcomment"] || !$validator::alnum(',;.:…-+–*?=()/&%$§"!@€[]{}<>\'ßüÜöÖäÄáÁéÉíÍóÓúÚàÀèÈìÌòÒùÙâÂêÊîÎôÔûÛ')->length(10,4000)->validate( $data["formcomment"] ) ){
        $errors['formcomment'] = "Please enter a valid about text";
        $labels["formcomment"] = $errors['formcomment'];
    }
    if( !$data["formcheck"] || $rightAnswer != $givenAnswer){
        $errors['formcheck'] = "Bitte korrekten Wert eingeben.";
        $labels["formcheck"] = "Wrong. New question: '".$questiondraw."'";
    }
}
$tpl->load("form.tpl");
```

Afterwards the variables and arrays are assigned (see in my initial post) and an if conditional is set either to send the form if all conditions are matched or render the form again with `$tpl->render();` if not . Hope that helps. I am still out of ideas what leads to that behaviour. Best regards Ralf

**Comment by titpetric** [comment]
Hi,

How do you modify these files (form.tpl)? Over samba/cifs? Some editor?

It might also be, that if you're doing it remotely via network mount (samba/cifs) or will fail because it re-writes the file and the file is empty or locked for reading at some point. If I understand what CodeKit does, it might be it - codekit refreshes the page continously so you can see changes as they happen in the code? Some samba settings that worked for me were

```
oplocks = no
level2 oplocks = no
```

My best bet, after having I guess several billion of successfully rendered templates, would be that you should catch the exception, usleep for some 100ms until no more exception (after file is saved completely, non empty, readable, compilable). It's a cludge for development, but generally I don't see any of these symptoms in production using rsync deployments for example, but those do atomic operations on files (replace).

I hope you figure it out, so far it seems to be not reproducible and caused by your setup, and not an actual bug in MiniTPL. I would look at the way you're writing the form.tpl (editor, remote filesystem) and see if there are settings which control the way the files are written on each save. Best guess: that's what's causing the error.

**Comment by rpkoller** [comment]
Hi Tit sorry for the late answer but i was trying to figure out the root cause of the issue as well as how to make it reproducible over the course of the last two days. But no luck so far - but somehow i got it at least working again on the remote end. 

Like you i guess it isn't a bug in MiniTPL. More or less i tend to believe it is caused by some sort of caching issue on the remote server. In my development process i haven't used the _nocache feature in minitpl so far. But i have to admit that i haven't had any issues at all locally with codekit and mamp. Everything worked and still works flawless even without the _nocache. 

But the problem was the remote part and the server config i have not much control settings wise. I've modified the files via an ftp client (transmit) and edited the files with sublime text directly remotely and copy and pasted my local changes into the file and then saved/uploaded the changes. so sometimes the setup choked remotely and minitpl spitted out thoses errors. the last time i got it working again i've set the _nocache (after you told me about). reloaded the page (the error still showed up). then i've removed it again and then replaced the whole template directory as well as the vendor directory with the one locally. and then after a few reloads it worked again. 

an odd issue overall. but as i said i tend to believe it has to do with some sort of caching issue :/ if i figure the root cause i will let you know.

Thanks for your help as well as thanks for that handy little tool!
