### ISSUE TITLE
What is the license for minitpl?

### ISSUE THREAD

**Issue by zakgreant** [titpetric/minitpl#5]
Hi Tit,

I'm reviewing the licensing for Crust's dependencies.

Can you tell me what license you are sharing minitpl under?

Cheers!
--zak

**Comment by titpetric** [comment]
Hi,

Asume wtfpl (public domain, anything goes). I’ll add the license file
shortly. If needed, I think I can relicense it to Apache-2.0 for Crust use.

Best,
Tit

**Comment by zakgreant** [comment]
Mornin' Tit,

WTFPL is just fine and is Apache-2.0 compatible. :)

**Comment by titpetric** [comment]
Great, added the LICENSE file in the root of the project.
